'area: backend':
  - changed-files:
      - any-glob-to-any-file: ['server/**']
'area: web-command':
  - changed-files:
      - any-glob-to-any-file: ['client/**']
'area: gis-python':
  - changed-files:
      - any-glob-to-any-file: ['gis/**']
'area: database':
  - changed-files:
      - any-glob-to-any-file: ['db/**', '**/migrations/**']
'area: devops':
  - changed-files:
      - any-glob-to-any-file: ['.github/**', 'docker-compose*.yml', 'Dockerfile*']
